num1 = input('Give me first number: ')
print(f"{num1}")
num2 = input('Give me second number: ')
print(f"{num2}")
addition = int(num1) + int(num2)
subtraction = int(num1) - int(num2)
multipication = int(num1) * int(num2)
division = int(num1) / int(num2)
integer_division = int(num1) // int(num2)
remainder = int(num1) % int(num2)
exponent = int(num1) ** int(num2)

print(f"{num1} + {num2} = {addition}")
print(f"{num1} - {num2} = {subtraction}")
print(f"{num1} * {num2} = {multipication}")
print(f"{num1} / {num2} = {division}")
print(f"{num1} // {num2} = {integer_division}")
print(f"{num1} % {num2} = {remainder}")
print(f"{num1} ** {num2} = {exponent}")